### ISSUE TITLE
Merge z najnowszej wersji z poprzedniego repo

### ISSUE THREAD

**Issue by kurak** [akinaj/frail_pwr#1]
W styczniu robiłem parę fixów (np. CylinderVolumeTrigger naprawdę jest cylindrem, a nie sferą) - warto byłoby zmerge'ować tutaj mastera z https://bitbucket.org/kurak/frail_pwr

**Comment by akinaj** [comment]
Bez obaw, pamiętałem o tym i właśnie się tym zajmuję :)
