### ISSUE TITLE
Struct failure

### ISSUE THREAD

**Issue by KamilLelonek** [akinaj/frail_pwr#3]
I'm not sure if this like is working correctly:
https://github.com/akinaj/frail_pwr/blob/master/src/code/mkd/Character.h#L35

**Comment by RadoMark** [comment]
+1

**Comment by speedcom** [comment]
+1

**Comment by cycki** [comment]
+1

**Comment by akinaj** [comment]
Dziękuję za zgłoszenie.
SensorCollision nie działa jeszcze jak należy stąd pewne śmieci :).
Poprawka zostanie wprowadzona w następnym commicie.

Pozdrawiam,
Artur Janik
